# Numpy 

In [1]:
a = [2,4,6,8,10]

In [2]:
b = []
for num in a:
    b.append(2*num)
b


[4, 8, 12, 16, 20]

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
type(a)

numpy.ndarray

In [5]:
2*a

array([ 2,  4,  6,  8, 10, 12])

In [6]:
data = np.random.randn(2,3)
data

array([[-1.03355653,  0.87012626,  1.11024972],
       [ 0.95724988, -1.7930366 , -0.2540541 ]])

In [11]:
data1 = np.arange(10)

In [12]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
data1.ndim

1

In [14]:
data.ndim

2

In [15]:
data.shape

(2, 3)

In [16]:
data1.shape

(10,)

In [17]:
b = np.array([[100]])

In [20]:
b.ndim

2

In [21]:
.shape

SyntaxError: invalid syntax (<ipython-input-21-abefa8d9bb1a>, line 1)

In [22]:
_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [23]:
_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
_3d.ndim

3

In [27]:
threeD = np.arange(64).reshape(4,4,4)

In [28]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [31]:
threeD = np.arange(30).reshape(3,5,2)

In [32]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [33]:
threeD = np.arange(50).reshape(5,5,2)

In [34]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [35]:
threeD.ndim

3

In [36]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6]])

In [37]:
m1.shape == m2.shape

True

In [38]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  5,  5]])

In [39]:
m1 + m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [13, 15, 17]])

In [40]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 2.        , 1.83333333]])

In [41]:
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 50, 66]])

In [42]:
m3 = np.arange(12).reshape(3,4)

In [43]:
m1@m3

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [49]:
m1.dot(m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [50]:
m1.shape

(4, 3)

In [51]:
m3.shape

(3, 4)

In [52]:
np.dot(m1,m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [53]:
a  =np.array([33,44,66],dtype="float32")

In [54]:
a

array([33., 44., 66.], dtype=float32)

In [55]:
a =np.array([33,44,66],dtype=np.float32)

In [56]:
a

array([33., 44., 66.], dtype=float32)

In [58]:
b = np.asarray(a,"int32")

In [59]:
b

array([33, 44, 66])

In [60]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [63]:
np.ones((5,4))*8

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [64]:
baa = np.full((4,4),7)

In [65]:
baa

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [66]:
jaa = np.ones_like(baa)

In [67]:
jaa

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
alist =  [1,2,3,4,5,6,7,8,9]

In [69]:
alist[6]

7

In [70]:
type(alist[2:4])

list

In [79]:
td = np.arange(36).reshape(6,6)

In [80]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
#td[r,c]
#td[--,--]
td[2:5,2:4]

array([[14, 15],
       [20, 21],
       [26, 27]])

In [83]:
td[4][5]

29

In [84]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])